# Generated by Django 5.0.7 on 2024-08-23 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FieldOfStudy',
            fields=[
                ('ID', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Major',
            fields=[
                ('ID', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=200)),
                ('FieldID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Demo.fieldofstudy')),
            ],
        ),
        migrations.CreateModel(
            name='University',
            fields=[
                ('ID', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=200)),
                ('Type', models.CharField(max_length=100)),
                ('Description', models.TextField(blank=True, null=True)),
                ('Logo', models.ImageField(upload_to='logos/')),
                ('Min_Score', models.DecimalField(decimal_places=2, max_digits=4)),
                ('Max_Score', models.DecimalField(decimal_places=2, max_digits=4)),
                ('Website', models.URLField()),
                ('Facebook', models.URLField()),
                ('Fields', models.ManyToManyField(related_name='universities', to='Demo.fieldofstudy')),
            ],
        ),
        migrations.CreateModel(
            name='UniMajor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200)),
                ('Score', models.DecimalField(decimal_places=2, max_digits=4)),
                ('Tuition_Fee', models.DecimalField(decimal_places=0, max_digits=12)),
                ('Subject_combination', models.CharField(max_length=3)),
                ('MajorID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Demo.major')),
                ('UniID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Demo.university')),
            ],
        ),
    ]
