# Generated by Django 5.1 on 2024-08-23 14:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Demo", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="unimajor",
            name="Subject_combination",
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name="unimajor",
            name="Tuition_Fee",
            field=models.DecimalField(
                blank=True, decimal_places=0, max_digits=12, null=True
            ),
        ),
    ]
