# Generated by Django 5.0.7 on 2024-08-27 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Demo', '0003_combination_region_rename_name_unimajor_m_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='Fields',
        ),
    ]
