# Generated by Django 5.1 on 2024-08-31 13:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("Demo", "0004_remove_university_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="combmajor",
            name="M_Name",
        ),
        migrations.RemoveField(
            model_name="university",
            name="Logo",
        ),
    ]
