# Generated by Django 5.1 on 2024-08-31 13:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("Demo", "0005_remove_combmajor_m_name_remove_university_logo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="major",
            name="ID",
            field=models.CharField(max_length=15, primary_key=True, serialize=False),
        ),
    ]
